version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - game-data:/app/data
    environment:
      - NODE_ENV=development
      - VITE_PORT=3000
      - HOST=0.0.0.0
      - STORAGE_PATH=/app/data
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  game-data:
    driver: local
